<template>
  <div v-loading="pageLoading" class="p-2">
    <el-card shadow="never">
      <el-form ref="aiYieldPredictionFormRef" :model="form" :rules="rules" :disabled="isDetail" label-width="auto">
        <el-form-item label="Production Season ID" prop="prodSeasonId">
          <div class="flex gap-2 flex-1">
            <el-input v-model="form.prodSeasonId" placeholder="Please enter Production Season ID" disabled />
            <SelectProductionSeason v-model="form.prodSeasonId"></SelectProductionSeason>
          </div>
        </el-form-item>
        <el-form-item label="Model Version" prop="modelVersion">
          <el-input v-model="form.modelVersion" maxlength="20" show-word-limit placeholder="Please enter AI Model Version" />
        </el-form-item>
        <el-form-item label="Model Name" prop="modelName">
          <el-input v-model="form.modelName" placeholder="Please enter Model Name" />
        </el-form-item>
        <el-form-item label="Predicted Yield (Quintal)" prop="predictedYieldQt">
          <el-input v-model="form.predictedYieldQt" placeholder="Please enter Predicted Yield (Quintal)" />
        </el-form-item>
        <el-form-item label="Predicted Yield Per Ha (quintal/ha)" prop="predictedYieldPerHa">
          <el-input-number
            style="width: 500px"
            :min="0"
            :max="9999999999.99"
            v-model="form.predictedYieldPerHa"
            placeholder="Please enter Predicted Yield Per Ha (quintal/ha)"
          />
        </el-form-item>
        <el-form-item label="Confidence (%)" prop="confidencePct">
          <el-input-number :min="0" style="width: 500px" :max="99999.99" v-model="form.confidencePct" placeholder="Please enter Confidence (%)" />
        </el-form-item>
        <el-form-item label="Prediction Range Min" prop="predictionRangeMin">
          <el-input v-model="form.predictionRangeMin" placeholder="Please enter Prediction Range Min" />
        </el-form-item>
        <el-form-item label="Prediction Range Max" prop="predictionRangeMax">
          <el-input v-model="form.predictionRangeMax" placeholder="Please enter Prediction Range Max" />
        </el-form-item>
        <el-form-item label="Weather Factor Score" prop="weatherFactorScore">
          <el-input v-model="form.weatherFactorScore" placeholder="Please enter Weather Factor Score" />
        </el-form-item>
        <el-form-item label="Soil Factor Score" prop="soilFactorScore">
          <el-input v-model="form.soilFactorScore" placeholder="Please enter Soil Factor Score" />
        </el-form-item>
        <el-form-item label="Management Factor Score" prop="managementFactorScore">
          <el-input v-model="form.managementFactorScore" placeholder="Please enter Management Factor Score" />
        </el-form-item>
        <el-form-item label="Pest & Disease Impact" prop="pestDiseaseImpact">
          <el-input v-model="form.pestDiseaseImpact" placeholder="Please enter Pest & Disease Impact" />
        </el-form-item>
        <el-form-item label="Input Features (JSON Format)" prop="inputFeatures">
          <el-input v-model="form.inputFeatures" type="textarea" placeholder="Please enter content" />
        </el-form-item>
        <el-form-item label="Generated At" prop="generatedAt">
          <el-date-picker
            clearable
            v-model="form.generatedAt"
            type="datetime"
            value-format="YYYY-MM-DD HH:mm:ss"
            placeholder="Please select Generated At"
          >
          </el-date-picker>
        </el-form-item>
        <el-form-item label="Generated By ID" prop="generatedBy">
          <el-input v-model="form.generatedBy" maxlength="20" show-word-limit placeholder="Please enter Generated By ID" />
        </el-form-item>
      </el-form>
      <div class="form-footer">
        <el-button v-if="isDetail" @click="cancel">Close</el-button>
        <template v-else>
          <el-button @click="cancel">Cancel</el-button>
          <el-button :loading="buttonLoading" type="primary" @click="submitForm">Save</el-button>
        </template>
      </div>
    </el-card>
  </div>
</template>

<script setup name="AiYieldPredictionForm" lang="ts">
import { getAiYieldPrediction, addAiYieldPrediction, updateAiYieldPrediction } from '@/api/demo/aiYieldPrediction';
import { AiYieldPredictionForm } from '@/api/demo/aiYieldPrediction/types';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const route = useRoute();
const router = useRouter();

const pageLoading = ref(false);
const buttonLoading = ref(false);
const aiYieldPredictionFormRef = ref<ElFormInstance>();

const isAdd = computed(() => route.path.endsWith('/add'));
const isEdit = computed(() => route.path.endsWith('/edit') || route.path.includes('/edit/'));
const isDetail = computed(() => route.path.endsWith('/detail') || route.path.includes('/detail/'));
const id = computed(() => (route.params.id as string) || '');

const listPath = computed(() => (route.meta.showPath as string) || route.path.replace(/\/[^/]+$/, ''));

const initFormData: AiYieldPredictionForm = {
  aiPredId: undefined,
  prodSeasonId: undefined,
  modelVersion: undefined,
  modelName: undefined,
  predictedYieldQt: undefined,
  predictedYieldPerHa: undefined,
  confidencePct: undefined,
  predictionRangeMin: undefined,
  predictionRangeMax: undefined,
  weatherFactorScore: undefined,
  soilFactorScore: undefined,
  managementFactorScore: undefined,
  pestDiseaseImpact: undefined,
  inputFeatures: undefined,
  generatedAt: undefined,
  generatedBy: undefined,
  deptId: undefined,
  remark: undefined
};

const form = ref<AiYieldPredictionForm>({ ...initFormData });

const rules = ref<ElFormRules>({
  aiPredId: [{ required: true, message: 'AI Prediction ID cannot be empty', trigger: 'blur' }],
  prodSeasonId: [{ required: true, message: 'Production Season ID cannot be empty', trigger: 'blur' }],
  modelVersion: [{ required: true, message: 'AI Model Version cannot be empty', trigger: 'blur' }],
  predictedYieldQt: [{ required: true, message: 'Predicted Yield (Quintal) cannot be empty', trigger: 'blur' }],
  confidencePct: [{ required: true, message: 'Confidence (%) cannot be empty', trigger: 'blur' }],
  generatedAt: [{ required: true, message: 'Generated At cannot be empty', trigger: 'blur' }],
  generatedBy: [{ required: true, message: 'Generated By ID cannot be empty', trigger: 'blur' }]
});

/** Load record for edit/detail mode */
const loadRecord = async () => {
  if (isAdd.value || !id.value) {
    form.value = { ...initFormData };
    return;
  }
  pageLoading.value = true;
  try {
    const res = await getAiYieldPrediction(id.value);
    Object.assign(form.value, res.data);
  } finally {
    pageLoading.value = false;
  }
};

/** Cancel Button */
const cancel = () => {
  router.push(listPath.value);
};

/** Submit Button */
const submitForm = () => {
  aiYieldPredictionFormRef.value?.validate(async (valid: boolean) => {
    if (!valid) return;
    buttonLoading.value = true;
    try {
      if (form.value.aiPredId) {
        await updateAiYieldPrediction(form.value);
      } else {
        await addAiYieldPrediction(form.value);
      }
      proxy?.$modal.msgSuccess('Operation successful');
      router.push({ path: listPath.value, query: { refresh: '1' } });
    } finally {
      buttonLoading.value = false;
    }
  });
};

onMounted(() => {
  loadRecord();
});
</script>

<style scoped>
.form-footer {
  display: flex;
  justify-content: center;
  gap: 12px;
  padding: 16px 0;
}
</style>
