<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover" class="search-card">
          <el-form ref="queryFormRef" :model="queryParams" label-position="top" class="search-section">
            <el-form-item label="Production Season ID" prop="prodSeasonId">
              <el-input prefix-icon="Search" v-model="queryParams.prodSeasonId" placeholder="Please enter Production Season ID" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="Model Version" prop="modelVersion">
              <el-input v-model="queryParams.modelVersion" placeholder="Please enter AI Model Version" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="Model Name" prop="modelName">
              <el-input v-model="queryParams.modelName" placeholder="Please enter Model Name" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <!-- <el-form-item label="Predicted Yield (Quintal)" prop="predictedYieldQt">
              <el-input
                v-model="queryParams.predictedYieldQt"
                placeholder="Please enter Predicted Yield (Quintal)"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Predicted Yield Per Ha (quintal/ha)" prop="predictedYieldPerHa">
              <el-input
                v-model="queryParams.predictedYieldPerHa"
                placeholder="Please enter Predicted Yield Per Ha (quintal/ha)"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Confidence (%)" prop="confidencePct">
              <el-input v-model="queryParams.confidencePct" placeholder="Please enter Confidence (%)" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="Prediction Range Min" prop="predictionRangeMin">
              <el-input
                v-model="queryParams.predictionRangeMin"
                placeholder="Please enter Prediction Range Min"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Prediction Range Max" prop="predictionRangeMax">
              <el-input
                v-model="queryParams.predictionRangeMax"
                placeholder="Please enter Prediction Range Max"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Weather Factor Score" prop="weatherFactorScore">
              <el-input
                v-model="queryParams.weatherFactorScore"
                placeholder="Please enter Weather Factor Score"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Soil Factor Score" prop="soilFactorScore">
              <el-input v-model="queryParams.soilFactorScore" placeholder="Please enter Soil Factor Score" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="Management Factor Score" prop="managementFactorScore">
              <el-input
                v-model="queryParams.managementFactorScore"
                placeholder="Please enter Management Factor Score"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Pest & Disease Impact" prop="pestDiseaseImpact">
              <el-input
                v-model="queryParams.pestDiseaseImpact"
                placeholder="Please enter Pest & Disease Impact"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Input Features (JSON Format)" prop="inputFeatures">
              <el-input
                v-model="queryParams.inputFeatures"
                placeholder="Please enter Input Features (JSON Format)"
                clearable
                @keyup.enter="handleQuery"
              />
            </el-form-item>
            <el-form-item label="Generated At" prop="generatedAt">
              <el-date-picker
                clearable
                v-model="queryParams.generatedAt"
                type="date"
                value-format="YYYY-MM-DD"
                placeholder="Please select Generated At"
              />
            </el-form-item>
            <el-form-item label="Generated By ID" prop="generatedBy">
              <el-input v-model="queryParams.generatedBy" placeholder="Please enter Generated By ID" clearable @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="Department ID" prop="deptId">
              <el-input v-model="queryParams.deptId" placeholder="Please enter Department ID" clearable @keyup.enter="handleQuery" />
            </el-form-item>
             -->
            <el-form-item class="search-actions">
              <el-button type="primary" icon="Search" @click="handleQuery">Search</el-button>
              <el-button icon="Refresh" @click="resetQuery">Reset</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="never">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="18"><span class="table-page-title"><el-icon class="table-page-title-icon"><Tickets /></el-icon> {{ ($route.meta.title || "") + " List" }}</span></el-col>
          <!-- <el-col :span="1.5" style="margin-left: auto">
            <el-button type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()" v-hasPermi="['demo:aiYieldPrediction:remove']"
              >Delete</el-button
            >
          </el-col> --> 
          <el-col :span="1.5" style="margin-left: auto; margin-right: 5px">
            <el-button type="primary" plain icon="Plus" @click="handleAdd" v-hasPermi="['demo:aiYieldPrediction:add']">Add</el-button>
          </el-col>
        </el-row>
      </template>

      <el-table v-loading="loading" border :data="aiYieldPredictionList" @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column label="AI Prediction ID" align="center" prop="aiPredId" v-if="true" />
        <el-table-column label="Production Season ID" align="center" prop="prodSeasonId" />
        <el-table-column label="Model Version" align="center" prop="modelVersion" />
        <el-table-column label="Model Name" align="center" prop="modelName" />
        <el-table-column label="Predicted Yield (Quintal)" align="center" prop="predictedYieldQt" />
        <el-table-column label="Predicted Yield Per Ha (quintal/ha)" align="center" prop="predictedYieldPerHa" />
        <el-table-column label="Confidence (%)" align="center" prop="confidencePct" />
        <el-table-column label="Prediction Range Min" align="center" prop="predictionRangeMin" />
        <el-table-column label="Prediction Range Max" align="center" prop="predictionRangeMax" />
        <el-table-column label="Weather Factor Score" align="center" prop="weatherFactorScore" />
        <el-table-column label="Soil Factor Score" align="center" prop="soilFactorScore" />
        <el-table-column label="Management Factor Score" align="center" prop="managementFactorScore" />
        <el-table-column label="Pest & Disease Impact" align="center" prop="pestDiseaseImpact" />
        <el-table-column label="Input Features (JSON Format)" align="center" prop="inputFeatures" />
        <el-table-column label="Generated At" align="center" prop="generatedAt" width="180">
          <template #default="scope">
            <span>{{ parseTime(scope.row.generatedAt, '{y}-{m}-{d}') }}</span>
          </template>
        </el-table-column>
        <el-table-column label="Generated By ID" align="center" prop="generatedBy" />
        <!-- <el-table-column label="Department ID" align="center" prop="deptId" />
        <el-table-column label="Remark" align="center" prop="remark" /> -->
        <el-table-column label="Actions" align="center" fixed="right" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="Edit" placement="top">
              <el-button link type="primary" icon="Edit" @click="handleUpdate(scope.row)" v-hasPermi="['demo:aiYieldPrediction:edit']"></el-button>
            </el-tooltip>
            <el-tooltip content="Delete" placement="top">
              <el-button
                link
                type="primary"
                icon="Delete"
                @click="handleDelete(scope.row)"
                v-hasPermi="['demo:aiYieldPrediction:remove']"
              ></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" :total="total" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" @pagination="getList" />
    </el-card>
    <!-- Add or Edit AI Yield Prediction Dialog -->
  </div>
</template>

<script setup name="AiYieldPrediction" lang="ts">
import {
  listAiYieldPrediction,
  getAiYieldPrediction,
  delAiYieldPrediction,
  addAiYieldPrediction,
  updateAiYieldPrediction
} from '@/api/demo/aiYieldPrediction';
import { AiYieldPredictionVO, AiYieldPredictionQuery, AiYieldPredictionForm } from '@/api/demo/aiYieldPrediction/types';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const route = useRoute();
const router = useRouter();

const aiYieldPredictionList = ref<AiYieldPredictionVO[]>([]);
const buttonLoading = ref(false);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<string | number>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);

const queryFormRef = ref<ElFormInstance>();
const aiYieldPredictionFormRef = ref<ElFormInstance>();

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: AiYieldPredictionForm = {
  aiPredId: undefined,
  prodSeasonId: undefined,
  modelVersion: undefined,
  modelName: undefined,
  predictedYieldQt: undefined,
  predictedYieldPerHa: undefined,
  confidencePct: undefined,
  predictionRangeMin: undefined,
  predictionRangeMax: undefined,
  weatherFactorScore: undefined,
  soilFactorScore: undefined,
  managementFactorScore: undefined,
  pestDiseaseImpact: undefined,
  inputFeatures: undefined,
  generatedAt: undefined,
  generatedBy: undefined,
  deptId: undefined,
  remark: undefined
};
const data = reactive<PageData<AiYieldPredictionForm, AiYieldPredictionQuery>>({
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    prodSeasonId: undefined,
    modelVersion: undefined,
    modelName: undefined,
    predictedYieldQt: undefined,
    predictedYieldPerHa: undefined,
    confidencePct: undefined,
    predictionRangeMin: undefined,
    predictionRangeMax: undefined,
    weatherFactorScore: undefined,
    soilFactorScore: undefined,
    managementFactorScore: undefined,
    pestDiseaseImpact: undefined,
    inputFeatures: undefined,
    generatedAt: undefined,
    generatedBy: undefined,
    deptId: undefined,
    params: {}
  },
  rules: {
    aiPredId: [{ required: true, message: 'AI Prediction ID cannot be empty', trigger: 'blur' }],
    prodSeasonId: [{ required: true, message: 'Production Season ID cannot be empty', trigger: 'blur' }],
    modelVersion: [{ required: true, message: 'AI Model Version cannot be empty', trigger: 'blur' }],
    predictedYieldQt: [{ required: true, message: 'Predicted Yield (Quintal) cannot be empty', trigger: 'blur' }],
    confidencePct: [{ required: true, message: 'Confidence (%) cannot be empty', trigger: 'blur' }],
    generatedAt: [{ required: true, message: 'Generated At cannot be empty', trigger: 'blur' }],
    generatedBy: [{ required: true, message: 'Generated By ID cannot be empty', trigger: 'blur' }]
  }
});

const { queryParams, form, rules } = toRefs(data);

/** Query AI Yield Prediction List */
const getList = async () => {
  loading.value = true;
  const res = await listAiYieldPrediction(queryParams.value);
  aiYieldPredictionList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};

/** Cancel Button */
const cancel = () => {
  reset();
  dialog.visible = false;
};

/** Form Reset */
const reset = () => {
  form.value = { ...initFormData };
  aiYieldPredictionFormRef.value?.resetFields();
};

/** Search Button Action */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};

/** Reset Button Action */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};

/** Multi-select Change */
const handleSelectionChange = (selection: AiYieldPredictionVO[]) => {
  ids.value = selection.map((item) => item.aiPredId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};

/** Add Button Action */
const handleAdd = () => {
  router.push({ name: 'AiYieldPredictionAdd' });
};

/** Edit Button Action */
const handleUpdate = (row?: AiYieldPredictionVO) => {
  const _aiPredId = row?.aiPredId || ids.value[0];
  router.push({ name: 'AiYieldPredictionEdit', params: { id: _aiPredId } });
};

/** Submit Button */
const submitForm = () => {
  aiYieldPredictionFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      buttonLoading.value = true;
      if (form.value.aiPredId) {
        await updateAiYieldPrediction(form.value).finally(() => (buttonLoading.value = false));
      } else {
        await addAiYieldPrediction(form.value).finally(() => (buttonLoading.value = false));
      }
      proxy?.$modal.msgSuccess('Operation successful');
      dialog.visible = false;
      await getList();
    }
  });
};

/** Delete Button Action */
const handleDelete = async (row?: AiYieldPredictionVO) => {
  const _aiPredIds = row?.aiPredId || ids.value;
  await proxy?.$modal.confirm('Are you sure to delete the AI Yield Prediction with ID "' + _aiPredIds + '"?').finally(() => (loading.value = false));
  await delAiYieldPrediction(_aiPredIds);
  proxy?.$modal.msgSuccess('Delete successful');
  await getList();
};

/** Export Button Action */
const handleExport = () => {
  proxy?.download(
    'demo/aiYieldPrediction/export',
    {
      ...queryParams.value
    },
    `aiYieldPrediction_${new Date().getTime()}.xlsx`
  );
};

onMounted(() => {
  getList();
});

onActivated(() => {
  if (route.query.refresh === '1') {
    getList();
  }
});
</script>

